export const ROUTES = {
  home: '/',
  about: '/about',
  collections: '/collections',
  collectionDetail: '/collections/:slug',
  services: '/services',
  serviceDetail: '/services/:slug',
  testimonials: '/testimonials',
  faq: '/faq',
  contact: '/contact',
  booking: '/book-appointment',
  bookingSuccess: '/book-appointment/success',
  privacy: '/privacy-policy',
  terms: '/terms',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  customer: '/dashboard',
  customerAppointments: '/dashboard/appointments',
  customerAppointmentDetail: '/dashboard/appointments/:id',
  customerFavorites: '/dashboard/favorites',
  customerMeasurements: '/dashboard/measurements',
  customerMessages: '/dashboard/messages',
  customerProfile: '/dashboard/profile',
  customerSettings: '/dashboard/settings',
  admin: '/admin',
  adminGallery: '/admin/gallery',
  adminCollections: '/admin/collections',
  adminServices: '/admin/services',
  adminAppointments: '/admin/appointments',
  adminCustomers: '/admin/customers',
  adminReviews: '/admin/reviews',
  adminMessages: '/admin/messages',
  adminStaff: '/admin/staff',
  adminReports: '/admin/reports',
  adminSettings: '/admin/settings',
  adminRoles: '/admin/roles',
  adminAnalytics: '/admin/analytics',
  adminAuditLogs: '/admin/audit-logs',
  adminSystemConfig: '/admin/system-config',
  notFound: '/404',
  unauthorized: '/unauthorized',
} as const

export type Role = 'customer' | 'staff' | 'admin' | 'super_admin'

export const ROLE_LABELS: Record<Role, string> = {
  customer: 'Customer',
  staff: 'Staff',
  admin: 'Admin',
  super_admin: 'Super Admin',
}
